- command: cat /etc/timezone
  register: tz_content

- name: set /etc/localtime to {{ timezone }}
  action: copy src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime

- name: set /etc/timezone to {{ timezone }}
  template: src=timezone.j2 dest=/etc/timezone
  when: tz_content.stdout.find('{{ timezone }}') == -1
  notify: update tzdata
