---
# First, we build a docker image with your ssh public key in root authorized keys
- hosts: local
  tasks:
  - shell: rm -rf ../docker/Dockerfile && rm -rf ../docker/authorized_keys
  - template: src=../docker/_Dockerfile dest=../docker/Dockerfile
  - copy: src={{ ssh_private_key }}.pub dest=../docker/authorized_keys force=no mode=0644
  - command: docker build -t developer_base_image ../docker
  - docker: image=developer_base_image name=developer_instance privileged=true state=running env="DISPLAY={{ display }}" publish_all_ports=true volumes="/tmp/.X11-unix:/tmp/.X11-unix"
  - wait_for: port={{docker_containers[0]['NetworkSettings']['Ports']['22/tcp'][0]['HostPort']}} delay=1

- hosts: docker_base
  user: developer
  sudo: yes
  port: "{{ hostvars['local_docker_builder'].docker_containers[0]['NetworkSettings']['Ports']['22/tcp'][0]['HostPort'] }}"
  tasks:
  - name: ensure minimal app apt dependencies are installed
    action: apt pkg={{item}} state=latest
    with_items:
      - python3-software-properties
      - software-properties-common
      - x11-utils
  - command: /usr/bin/add-apt-repository universe
  - command: /usr/bin/add-apt-repository multiverse
  - apt: update_cache=yes upgrade=dist
#We allow X11 forwarding
  - copy: dest=/root/.Xauthority content="" owner=root group=root mode=0600
